<?php

namespace Travel\TravelBundle\Repository;

/**
 * CarburantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarburantRepository extends \Doctrine\ORM\EntityRepository
{
}
