<?php

namespace Travel\TravelBundle\Repository;

/**
 * ConducteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConducteurRepository extends \Doctrine\ORM\EntityRepository
{
}
