<?php

namespace Travel\TravelBundle\Repository;

/**
 * Ligne_maintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ligne_maintenanceRepository extends \Doctrine\ORM\EntityRepository
{
}
